#!/usr/bin/env bash
set -euo pipefail

# prepare.sh — Clone reference repos and set up test fixtures for oxvelte.
# Run once before starting development. Do NOT modify this file.

VENDOR_DIR="./vendor"
SVELTE_REPO="https://github.com/sveltejs/svelte.git"
ESLINT_REPO="https://github.com/sveltejs/eslint-plugin-svelte.git"

echo "=== Oxvelte Preparation ==="
echo ""

# ─── Clone svelte ───────────────────────────────────────────────────────────
if [ -d "$VENDOR_DIR/svelte" ]; then
    echo "[svelte] Already cloned. Pulling latest..."
    cd "$VENDOR_DIR/svelte" && git pull --ff-only && cd ../..
else
    echo "[svelte] Cloning sveltejs/svelte (sparse checkout — tests + compiler types only)..."
    mkdir -p "$VENDOR_DIR"
    git clone --depth 1 --filter=blob:none --sparse "$SVELTE_REPO" "$VENDOR_DIR/svelte"
    cd "$VENDOR_DIR/svelte"
    git sparse-checkout set \
        packages/svelte/tests/parser-modern \
        packages/svelte/tests/parser-legacy \
        packages/svelte/src/compiler/types
    cd ../..
fi

PARSER_MODERN_COUNT=$(find "$VENDOR_DIR/svelte/packages/svelte/tests/parser-modern/samples" -name "input.svelte" 2>/dev/null | wc -l)
PARSER_LEGACY_COUNT=$(find "$VENDOR_DIR/svelte/packages/svelte/tests/parser-legacy/samples" -name "input.svelte" 2>/dev/null | wc -l)
echo "[svelte] Found $PARSER_MODERN_COUNT modern parser tests, $PARSER_LEGACY_COUNT legacy parser tests."

# ─── Clone eslint-plugin-svelte ─────────────────────────────────────────────
if [ -d "$VENDOR_DIR/eslint-plugin-svelte" ]; then
    echo "[eslint-plugin-svelte] Already cloned. Pulling latest..."
    cd "$VENDOR_DIR/eslint-plugin-svelte" && git pull --ff-only && cd ../..
else
    echo "[eslint-plugin-svelte] Cloning sveltejs/eslint-plugin-svelte (sparse checkout — rules + tests)..."
    git clone --depth 1 --filter=blob:none --sparse "$ESLINT_REPO" "$VENDOR_DIR/eslint-plugin-svelte"
    cd "$VENDOR_DIR/eslint-plugin-svelte"
    git sparse-checkout set \
        packages/eslint-plugin-svelte/src/rules \
        packages/eslint-plugin-svelte/tests
    cd ../..
fi

RULE_COUNT=$(find "$VENDOR_DIR/eslint-plugin-svelte/packages/eslint-plugin-svelte/src/rules" -name "*.ts" -not -name "index.ts" 2>/dev/null | wc -l)
echo "[eslint-plugin-svelte] Found $RULE_COUNT lint rule implementations."

# ─── Copy parser test fixtures into fixtures/ ───────────────────────────────
PARSER_FIXTURE_DIR="fixtures/parser"
mkdir -p "$PARSER_FIXTURE_DIR/modern" "$PARSER_FIXTURE_DIR/legacy"

echo "[fixtures] Copying parser test fixtures..."
if [ -d "$VENDOR_DIR/svelte/packages/svelte/tests/parser-modern/samples" ]; then
    cp -r "$VENDOR_DIR/svelte/packages/svelte/tests/parser-modern/samples/"* "$PARSER_FIXTURE_DIR/modern/" 2>/dev/null || true
fi
if [ -d "$VENDOR_DIR/svelte/packages/svelte/tests/parser-legacy/samples" ]; then
    cp -r "$VENDOR_DIR/svelte/packages/svelte/tests/parser-legacy/samples/"* "$PARSER_FIXTURE_DIR/legacy/" 2>/dev/null || true
fi

# ─── Copy lint rule test fixtures into fixtures/ ────────────────────────────
LINT_FIXTURE_SRC="$VENDOR_DIR/eslint-plugin-svelte/packages/eslint-plugin-svelte/tests/fixtures/rules"
LINT_FIXTURE_DST="fixtures/linter"
mkdir -p "$LINT_FIXTURE_DST"

if [ -d "$LINT_FIXTURE_SRC" ]; then
    echo "[fixtures] Copying lint rule test fixtures..."
    cp -r "$LINT_FIXTURE_SRC/"* "$LINT_FIXTURE_DST/" 2>/dev/null || true
fi

# ─── Lock down permissions ──────────────────────────────────────────────────
echo "[permissions] Making vendor/ read-only..."
chmod -R a-w "$VENDOR_DIR" 2>/dev/null || true

echo "[permissions] Making copied fixture dirs read-only..."
chmod -R a-w "fixtures/" 2>/dev/null || true

# ─── Generate fixture checksums ─────────────────────────────────────────────
echo "[checksums] Generating fixture integrity checksums..."
bash verify_fixtures.sh --init

# ─── Install git pre-commit hook ────────────────────────────────────────────
if [ -d ".git" ]; then
    HOOK_FILE=".git/hooks/pre-commit"
    echo "[hook] Installing pre-commit fixture verification hook..."
    cat > "$HOOK_FILE" << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by prepare.sh — verifies test fixtures are unmodified before commit.
echo "Running fixture integrity check..."
bash verify_fixtures.sh --verify
if [ $? -ne 0 ]; then
    echo ""
    echo "COMMIT BLOCKED: Test fixtures have been modified."
    echo "Restore them with: bash prepare.sh"
    exit 1
fi
HOOK
    chmod +x "$HOOK_FILE"
fi

# ─── Summary ────────────────────────────────────────────────────────────────
echo ""
echo "=== Preparation complete ==="
echo "  vendor/svelte                  — parser test fixtures + AST types (READ-ONLY)"
echo "  vendor/eslint-plugin-svelte    — lint rules + test fixtures (READ-ONLY)"
echo "  fixtures/parser/               — parser test inputs copied (READ-ONLY)"
echo "  fixtures/linter/               — lint test inputs copied (READ-ONLY)"
echo "  .fixtures.sha256               — integrity checksums"
echo "  .git/hooks/pre-commit          — blocks commits if fixtures modified"
echo ""
echo "You can now run: cargo build"
