Output assets/demo-eslint.gif
Set FontSize 22
Set Width 450
Set Height 300
Set Theme "Catppuccin Mocha"
Set Padding 30
Set TypingSpeed 40ms
Set Shell "bash"

Hide
Type `export PS1="\033[1;35m❯\033[0m "` Enter
Type `alias eslint="bash demo/run-eslint-timed.sh"` Enter
Type "clear" Enter
Show
Sleep 300ms

Type `echo -e "\033[1meslint-plugin-svelte\033[0m"` Enter
Sleep 600ms
Type "eslint src/"
Sleep 400ms
Enter
Sleep 5s
Sleep 2s
